### ISSUE TITLE
a problem in running a job

### ISSUE THREAD

**Issue by liliang0908** [cnobles/iGUIDE#75]
Hi Chris,

I met a problem when running iguide, the eval.log(error) as follows:

iGUIDE Evaluation Inputs:
Loading dependencies.
Importing experimental data and configurations.
Error in download.file(input, tmpFile <- tempfile(), method = method,  :
  cannot open URL 'http://bushmanlab.org/assets/doc/allOnco_Feb2017.tsv'
Calls: suppressMessages ... withCallingHandlers -> loadRefFiles -> <Anonymous> -> download.file
In addition: Warning message:
In download.file(input, tmpFile <- tempfile(), method = method,  :
  URL 'http://bushmanlab.org/assets/doc/allOnco_Feb2017.tsv': status was 'Couldn't resolve host name'
Execution halted

So it is likely that the URL 'http://bushmanlab.org/assets/doc/allOnco_Feb2017.tsv cant be connected, how to deal with it?

By the way, I have another two question about iGUIDE:
1 Article mentioned that:” deliver 100 to 500 pmols of dsODN along with the protein”, if i use 3*10^6 cell in 20 µl system with PNP, what is the recommand pmol of dsODN?
2 Cluster generation of my iGUIDE library is poor when sequencing, the quality of read2 is bad(sequence of read2 sequencing primer is provided in the iGUIDE article), do you have any suggestions for this problem?

You reply will be greatly appreciated!

best,
Liang

**Comment by cnobles** [comment]
Hi Liang,

The error is occurring due to the page being down. In my experience this is only a temporary issue. I would recommend just trying the link separate from the processing, and when you can get to the file through a browser, then try to finish your processing. I will reach out to the Bushman Lab a see if there is an issue. 

In the future, you can download the files and have them within the iGUIDE directory (or your working directory) and provide a path to the file rather than a web link. Additionally, here is a proper format (only chose one format per file) to include in the config file should you want to change from web links to local files (you'll need the file first to do the local version):

```
# Web address format
oncoGeneList :
    file : "http://bushmanlab.org/assets/doc/allOnco_Feb2017.tsv"
    symbolCol : "symbol"

# Local file format
oncoGeneList :
    file : "etc/allOnco_Feb2017.tsv"
    symbolCol : "symbol"
```

Regarding your question about the dsODN concentration, this is actually something I would highly recommend you try to optimize in the lab prior to sequencing. This can save you a lot of time and money.  I would recommend doing a few conditions and then isolating genomic DNA. Design primers for your on-target side and then use the genomic material as template. The dsODN has a restriction site in the middle (...) so if you have solid incorporation of the oligo in the the genome, you should be able to digest the PCR amplicon and resolve this on a DNA gel. You can use this process to optimize your reaction conditions for when you have the desired amount of dsODN incorporated. Under those conditions, you will likely want to run your assay. Not everyone uses the same protocol for gene editing, as you've pointed out, so taking a step back and optimizing the protocol for your own use can be useful. 

This last point might actually be able to address your second additional question. If the cluster generation is poor, you may have low yield in your libraries due to an inefficient amount of starting template. Additionally, the R2 read has a challenge of sequencing through a constant sequence region (super low diversity) which heavily impacts the output. I recommend checking which levels of phiX may be helpful, we frequently used 5-10% for the manuscript samples sequenced on a MiSeq. I suspect greater challenges for diversity if sequencing on a 2-color chemistry platform, such as the NextSeq.

Best,
Chris

**Comment by liliang0908** [comment]
Hi Chris,

Appreciate your useful recommendations!
I have few more questions about sequencing of  iguide.
1 My sequence data containng ODN is low ratio, I suspect the ODN amount in CRISPR added is too small, it reduce an inefficient amount of starting template as you mentioned. what is your viewpoint about it?
2 I got a lot of sequencing read2 sequence(after QC and trim_adapter of NGS) like this:  ACATATGACAACTCAATTAAACGCGAGCAGGAGGC TGCTGTAGTTTATT
it is short and a few base followed the ODN sequence , is it normal? Is this induced by the low quality iguide library?
3 Article mentioned that:”Transfer sample DNA directly from PCR1 reactions to respective replicate PCR2 reactions",so dose it mean that we don't need to purify the  PCR1 reactions,the crude PCR1 reactions could be used as template directly? Will the primers in crude  PCR1 reactions influence the PCR2 reaction,is it a reason inducing short sequence that question 2 mentioned?

Looking forward your reply.

best,
Liang

**Comment by cnobles** [comment]
Hi Liang,

Happy to share my general thoughts on your questions:

1. Low ratio of ODN in sequencing data: This could be caused by what you suspect, too little ODN in CRISPR experiment. This could also be caused by a number of other issues. Low CRISPR activity could be one example, poor PCR efficiency could be another. I would recommend trying to design an experiment, pre-sequencing, to measure the amount of ODN incorporation at your target site. This can be done by designing a targeted PCR primers to your target site, amplifying your post-ODN exposed material (that you would use for input into the iGUIDE assay), then treat with a restriction enzyme (would have to look at the ODN sequence to see which one it was), and resolve on a gel. The intensities could help you with understanding the amount of incorporation, and combined with another assay like TIDE, you could estimate your CRISPR efficiency and see if that's a issue as well. PCR efficiency could be judged by the amount of product your getting for libraries, which may always be on the low side anyway, but testing a few conditions with a standardized library could indicate optimal PCR conditions for your lab.

2. Additional sequence following ODN: Not quite sure here. Possibly optimizing the PCR parameters may make this go away, but  I can't say this was an issue I notice. I also can't say that it didn't exist in our work, I just simply didn't notice it.

3. I do believe that we did not purify PCR1 product prior to using it as template for PCR2, but knowing that iGUIDE is very similar to another assay that we did in the lab, INSPIIRED, that focuses on capturing lentiviral integration sites, I know it can be done. In the other assay, we do not purify from PCR1 to PCR2. 

Hope that helps and the information is not too late. 

Best,
Chris
