### ISSUE TITLE
running iguide with mouse datasets: Error in if (grepl(".rds$", ref$file)) { : argument is of length zero 

### ISSUE THREAD

**Issue by weihongqi** [cnobles/iGUIDE#80]
Dear Team,

iguide has been used successfully in my lab for human datasets. Thanks. It is a nice and useful tool.

Now we are testing iguide in analyzing mouse datasets. The mm10 reference genome was installed from Bioconductor BSgenome. The analysis ran till the evaluation step, and failed with: Error in if (grepl(".rds$", ref$file)) { : argument is of length zero

In the config file the refGene and the other two gene lists were commented out, since I don't know where to get the rds and tsv files for mm10. But the error message seemed to suggest that the refGene.rds is required for the analysis. Is this correct? If it is, could you please let me know if you have the mouse refGene.rds for downloading? Or which input file should be used to generate such genomicRange object?

![image](https://user-images.githubusercontent.com/8567021/106524984-954ae780-64e3-11eb-8bca-737cf66c6210.png)

If it is not due to the refGene.rds, do you have further suggestions on debugging? Your input will be highly appreciated.

Kind regards,

Weihong

**Comment by cnobles** [comment]
Hi Weihong,

You'll want to download the related data sets from UCSC or NCBI. The default formats for these files are from UCSC genome browser tables. But if you take a look at them, they contain range information (which chromosome, start, and stop positions), as well as a symbol column that you can specify. So all you really need to find is a reference gene annotation set that you want to use for mouse, based on the same reference genome, and then format the tables here. There are several formats that are acceptable to include (rds, csv, or tsv). There is a section on this in the documentation, pasted below:

`refGenes / oncoGeneList / specialGeneList`
These are special reference files in either text or BioConductoR’s GenomicRanges objects. They can be in an ‘.rds’ format or table format (‘.csv’ or ‘.tsv’). The file parameter should indicate the file path to the file (relative paths should be relative to the SnakeFile), and the symbolCol parameter should indicate the column in the data object which contains the reference names to be used in the analysis.

The oncoGeneList and the specialGeneList are simply lists that should contain subsets of the refGene list you choose. Double check the names in these lists are present in your refGene list, otherwise you won't get accurate annotations.

Best,
Chris

**Comment by weihongqi** [comment]
Dear Chris,

Thanks.

I downloaded the mm10 knowngenes from UCSC genome browser tables as a tab delimited text file, converted it to a GRange object, saved it as a rds file. Then I subet the downloaded text file with the mouse gene names corresponding to those in the human oncoGeneList and the specialGeneList. 

The evaluation R script could read in these files properly:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/8567021/108357648-0251c300-71ee-11eb-94b6-e16f7c3349dc.png">

 "Importing experimental data and configurations" was successful and the analysis continued. But the fisher exact tests failed with the following error

Error in fisher.test(mat) : 
  all entries of 'x' must be nonnegative and finite
Calls: p.adjust -> sapply -> sapply -> lapply -> FUN -> fisher.test
Execution halted

my geneList looks like the following:
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/8567021/108357541-dc2c2300-71ed-11eb-911a-230a627eca26.png">

Do you know how to debug this? Is it possible to turn off gene set enrichment analysis? 

Many thanks in advance,

Weihong

**Comment by cnobles** [comment]
Hi Weihong, I know it's been some time. I took another look at our conversation and was wondering if the issue may just come from mismatching between the gene sets. The standard format for gene names in the equivalent human gene list files is that the gene names are all caps, where your format for the murine gene list shows lower case gene names (i.e. cmp1 and not CMP1). Not sure if this is the issue, but I've added a component when importing gene lists so that they will always be converted to uppercase format. (Commit 216da140648822e2fc28e53fdefe595b456b3829). I'll close this issue for now, but if you or others ever have the same issue, then I'm happy to reopen it.
